services:
  - type: web
    name: openai-chatbot
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
